default_language_version.python = "3.12"

[[repos]]
repo = "local"
hooks = [
  # Backend hooks
  {
    id = "ruff-format",
    name = "ruff-format",
    language = "system",
    entry = "ruff format",
    files = "^backend/.*\\.py$",
  },
  {
    id = "ruff",
    name = "ruff",
    language = "system",
    entry = "ruff check --fix",
    files = "^backend/.*\\.py$",
  },
  {
    id = "mypy",
    name = "mypy",
    language = "system",
    entry = "mypy --config-file backend/pyproject.toml backend",
    files = "^backend/.*\\.py$",
    pass_filenames = false,
  },

  # Frontend hooks
  {
    id = "prettier",
    name = "prettier",
    language = "system",
    entry = "npm run format:write --prefix frontend",
    files = "^frontend/.*\\.(js|jsx|ts|tsx|css|json)$",
    pass_filenames = false,
  },
  {
    id = "eslint",
    name = "eslint",
    language = "system",
    entry = "npm run lint:fix --prefix frontend",
    files = "^frontend/.*\\.(js|jsx|ts|tsx)$",
    pass_filenames = false,
  },
  {
    id = "typecheck",
    name = "typecheck",
    language = "system",
    entry = "npm run typecheck --prefix frontend",
    files = "^frontend/.*\\.(ts|tsx)$",
    pass_filenames = false,
  },
]